### ISSUE TITLE
TypeError: Cannot destructure property `readFile` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by rahul70392** [near-examples/poker#1]
I installed the near-shell npm module using 'npm install -g near-shell', But I am getting Type error when checking the near version 'near --version' -

/usr/local/lib/node_modules/near-shell/commands/dev-deploy.js:4
const { readFile, writeFile, mkdir } = require('fs').promises;
        ^

TypeError: Cannot destructure property `readFile` of 'undefined' or 'null'.
    at Object.<anonymous> (/usr/local/lib/node_modules/near-shell/commands/dev-deploy.js:4:53)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/near-shell/bin/near-cli.js:195:14)
    at Module._compile (module.js:653:30)

**Comment by amgando** [comment]
thanks for posting @rahul70392, can you share some of your system details with us here please?

you can run this command to share the version of Node.js you are using

```
node -v
```

and this command for a few more details about your operating system

```
npx systeminformation
```
(see more here: https://www.npmjs.com/package/systeminformation)

the `os` node of the resulting JSON object will be useful for us to try to reproduce this error.  here's the report from my system

```
{
  "os": {
    "platform": "darwin",
    "distro": "Mac OS X",
    "release": "10.15.5",
    "codename": "macOS Catalina",
    "kernel": "19.5.0",
    "arch": "x64",
    "hostname": "bigbuk.local",
    "codepage": "UTF-8",
    "logofile": "apple",
    "serial": "54F1A78D-6F41-32BD-BFED-4381F9F6E2EF",
    "build": "19F101",
    "servicepack": "",
    "uefi": true
  }
```

**Comment by mfornet** [comment]
This issue is more appropriate for [near-shell](https://github.com/near/near-shell) repository.
